version: "3"

services:
  event-store:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:20.6.1-alpha.0.49-buster-slim
    ports:
    - 2113:2113
    volumes:
    - ./eventstore:/eventstore
    environment:
    - "EVENTSTORE_RUN_PROJECTIONS=All"
    - "EVENTSTORE_START_STANDARD_PROJECTIONS=true"
    - "EVENTSTORE_DB=/eventstore/data"
    - "EVENTSTORE_CERTIFICATE_FILE=/eventstore/certs/eventstore.p12"
    - "EVENTSTORE_TRUSTED_ROOT_CERTIFICATES_PATH=/eventstore/certs/"
    - "EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true"
    env_file:
      - .env