# common volume to manage asp.net data protection keys
{{- $name := print $.Release.Name "-data-protection" }}
{{- $labels := include "standard.labels" . }}
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ $name }}
  labels: {{ $labels | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "100Mi"
