name: cd-landing-page

on:
  push:
    branches:
      - master

    paths:
      - "landing-page/src/**"
      - ".github/workflows/cd-landing-page.yml"

env:
  IMAGE_NAME: landing-page-ytqsl
  IMAGE_ID: ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ IMAGE_NAME }}:v

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image
        run: docker pull $IMAGE_ID || true

      - name: Build image
        working-directory: ./landing-page/src/
        run: |
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ steps.tag_version.outputs.new_tag }}" | sed 's/^[^:v]*:v//')
 
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION          
 
          tar -czh . | docker build --tag $IMAGE_ID:latest --cache-from=$IMAGE_ID --build-arg VERSION=$TAG -
          docker tag $IMAGE_ID:latest $IMAGE_ID:$VERSION

      - name: Push image
        run: |
          docker push --all-tags $IMAGE_ID