name: cd-landing-page

on:
  push:
    branches:
      - master

    paths:
      - "landing-page/src/**"
      - ".github/workflows/cd-landing-page.yml"

env:
  IMAGE_NAME: landing-page-ytqsl

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ env.IMAGE_NAME }}:v

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image repository
        run: |
          # Change all uppercase to lowercase
          export DOCKER_REPOSITORY=$(${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }} | tr '[A-Z]' '[a-z]'))
          echo "DOCKER_REPOSITORY=$DOCKER_REPOSITORY"
          
      - name: Pull image
        run: docker pull $DOCKER_REPOSITORY:latest || true

      - name: Build image
        working-directory: ./landing-page/src/
        run: |
          VERSION=$(echo "${{ steps.tag_version.outputs.new_tag }}" | sed 's/^[^:v]*:v//')
 
          echo DOCKER_REPOSITORY=$DOCKER_REPOSITORY
          echo VERSION=$VERSION          
 
          tar -czh . | docker build --tag $DOCKER_REPOSITORY:latest --cache-from=$DOCKER_REPOSITORY:latest --build-arg VERSION=$TAG -
          docker tag $DOCKER_REPOSITORY:latest $DOCKER_REPOSITORY:$VERSION

      - name: Push image
        run: |
          docker push --all-tags $DOCKER_REPOSITORY
