name: ci-responders-portal-ui

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "responders/src/UI/**"
      - ".github/workflows/ci-responders-portal-ui.yml"

env:
  IMAGE_NAME: responders-portal-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Build image
        working-directory: ./responders/src/UI
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
