name: ci-responders-portal-ui

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "src/*.Responders.UI/**"
      - "src/build/Responders/Responders.UI.Dockerfile"
      - "src/build/Responders/Caddyfile"
      - ".github/workflows/ci-responders-portal-ui.yml"

env:
  IMAGE_NAME: responders-portal-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: ./src
        run: docker build . --file ./build/Responders/Responders.UI.Dockerfile --tag $IMAGE_NAME
