name: ci-responders-portal-api

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "responders/src/API/**"
      - "shared/src/**"
      - ".github/workflows/ci-responders-portal-api.yml"

env:
  IMAGE_NAME: responders-portal-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Build image
        working-directory: ./responders/src/API
        run: tar -czh . | docker build --tag $IMAGE_NAME -
