name: ci-registrants-portal-ui

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "src/*.Registrants.UI/**"
      - "src/build/Registrants/Registrants.UI.Dockerfile"
      - "src/build/Registrants/Caddyfile"
      - ".github/workflows/ci-registrants-portal-ui.yml"

env:
  IMAGE_NAME: registrants-portal-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: ./src
        run: docker build . --file src/build/Registrants/Registrants.UI.Dockerfile --tag $IMAGE_NAME
