name: ci-suppliers-portal-api

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "suppliers/src/API/**"
      - ".github/workflows/ci-suppliers-portal-api.yml"

env:
  IMAGE_NAME: suppliers-portal-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Build image
        working-directory: ./suppliers/src/API
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg GITHUB_NUGET_USERNAME=github --build-arg GITHUB_NUGET_PAT=${{ secrets.GITHUB_TOKEN }}
